language: php
php:
  - 5.3
  - 5.6
  - hhvm
env:
  - QUASSEL_HOST=127.0.0.1:4242
install:
  - sudo apt-get -qq update && sudo apt-get --no-install-recommends -qq install -y quassel-core
  - composer install --prefer-source --no-interaction
script:
  - sudo /etc/init.d/quasselcore status || sudo /etc/init.d/quasselcore start
  - sudo /etc/init.d/quasselcore status || sleep 2
  - phpunit --coverage-text
