language: php

# lock distro so new future defaults will not break the build
dist: trusty

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: hhvm-3.18
  allow_failures:
    - php: hhvm-3.18

sudo: true

env:
  - QUASSEL_HOST=127.0.0.1:4242

install:
  - sudo apt-get -qq update && sudo apt-get --no-install-recommends -qq install -y quassel-core
  - composer install --no-interaction

script:
  - sudo /etc/init.d/quasselcore status || sudo /etc/init.d/quasselcore start
  - sudo /etc/init.d/quasselcore status || sleep 2
  - vendor/bin/phpunit --coverage-text
