name: CI

on:
  push:
  pull_request:

env: 
  QUASSEL_HOST: 127.0.0.1:4242

jobs:
  PHPUnit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
          - 7.3
          - 7.2
          - 7.1
          - 7.0
          - 5.6
          - 5.5
          - 5.4
          - 5.3
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: sudo apt-get -qq update || true # update package list and ignore temporary network errors
      - run: sudo apt-get --no-install-recommends -qq install -y quassel-core   
      - run: composer install
      - run: sudo /etc/init.d/quasselcore status || sudo /etc/init.d/quasselcore start
      - run: sudo /etc/init.d/quasselcore status || sleep 2
      - run: vendor/bin/phpunit --coverage-text

  PHPUnit-hhvm:
    name: PHPUnit (HHVM)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: azjezz/setup-hhvm@v1
        with:
          version: lts-3.30
      - run: sudo apt-get -qq update || true # update package list and ignore temporary network errors
      - run: sudo apt-get --no-install-recommends -qq install -y quassel-core      
      - run: hhvm $(which composer) install
      - run: sudo /etc/init.d/quasselcore status || sudo /etc/init.d/quasselcore start
      - run: sudo /etc/init.d/quasselcore status || sleep 2
      - run: hhvm vendor/bin/phpunit
